### ISSUE TITLE
Small bug in LFO mod source serialization/deserialization

### ISSUE THREAD

**Issue by coffeeshopped** [stuartkeith/esq1#1]
In my tests, it looks like the pairs of bits that get broken up for the mod source of an LFO are swapped, so that serialized patches are corrupting that parameter. You just need to swap what you're doing with your modulation_source_0 and modulation_source_1 variables in serialize and deserialize. So, here: https://github.com/stuartkeith/esq1/blob/master/esq1.py#L312

Change those two lines to:

```
    bytes.append(modulation_source_1 + self.levels[0].value)
    bytes.append(modulation_source_0 + self.levels[1].value)
```

... and in deserialize (https://github.com/stuartkeith/esq1/blob/master/esq1.py#L335):

```
    self.modulation_source.value = modulation_source_1 +\
        (modulation_source_0 << 2)
```

That fixes it for me.

I'm building an ESQ-1 editor of my own, so thanks for this wonderful example!

**Comment by stuartkeith** [comment]
Thank you for this - I checked and you're right. I'll push the fix. It's good to know somebody's found this useful!
